name: Processes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Process1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Process1
        run: python3 Py_scr/Process1.py

  Process2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Process1
        run: python3 Py_scr/Process2.py


  Process3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Process1
        run: python3 Py_scr/Process3.py

  Process4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Process4
        run: python3 Py_scr/Process4.py

  Process5:
    runs-on: ubuntu-latest
    needs: [ Process1,Process2,Process3,Process4 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Process5
        run: python3 Py_scr/Process5.py

      - name: Commit files
        run: |
            git config --global user.email anapiyaevs0519@gmail.com"
            git config --global user.name "sanzhik22"
            git config --global credential.helper cache
            git clone https://${{secrets.token-new}}@github.com/sanzhik22/Optimizing-by-paralel-gitactions
            git add data
            git commit -m "$(date)"
            git push
